// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WakeCommerce.Api.Data;

#nullable disable

namespace WakeCommerce.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227102527_SeedProdutos")]
    partial class SeedProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WakeCommerce.Api.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estoque = 10,
                            Nome = "Teclado",
                            Valor = 259.90m
                        },
                        new
                        {
                            Id = 2,
                            Estoque = 25,
                            Nome = "Mouse",
                            Valor = 120.00m
                        },
                        new
                        {
                            Id = 3,
                            Estoque = 5,
                            Nome = "Monitor",
                            Valor = 899.00m
                        },
                        new
                        {
                            Id = 4,
                            Estoque = 15,
                            Nome = "Headset",
                            Valor = 199.90m
                        },
                        new
                        {
                            Id = 5,
                            Estoque = 8,
                            Nome = "Webcam",
                            Valor = 350.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
